version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/pptruser
    ports:
      - 8080:8080
    volumes:
      - .:/home/pptruser
    networks:
      - whats-app-bot


networks:
  whats-app-bot:
    driver: bridge